"""Initial2

Revision ID: bb6aa41cd0bd
Revises: 84a5545be1e1
Create Date: 2024-07-18 09:51:32.355135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6aa41cd0bd'
down_revision: Union[str, None] = '84a5545be1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('city')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
